url: anandia234.github.io
baseurl: ''

# Site settings
title: Anandiamy's Portofolio
email: anandiamy@gmail.com
description: "Anandia's portofolio"

# Team names, titles and social links
people:
- name: Anandia Muhammad Yudhistira
  pic: 1
  position: Lead Designer
  social:
    - title: twitter
      url: #
    - title: facebook
      url: fb.com/anandiamy
    - title: stack-overflow
      url: #

- name: Anandia Muhammad Yudhistira 2
  pic: 2
  position: Lead Marketer
  social:
    - title: twitter
      url: #
    - title: facebook
      url: fb.com/anandiamy
    - title: linkedin
      url: #

- name: Anandia Muhammad Yudhistira 3
  pic: 3
  position: Lead Developer
  social:
    - title: twitter
      url: #
    - title: facebook
      url: fb.com/anandiamy
    - title: google-plus
      url: #

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: twitter
    url: #
  - title: facebook
    url: fb.com/anandiamy
  - title: stack-overflow
    url: #
  - title: bitbucket 
    url: #
  - title: github
    url: https://github.com/anandia234

# Postal address (add as many lines as necessary)
address:
  - line: 3481 Melrose Place
  - line: Beverly Hills, CA 90210

# Build settings
markdown: kramdown
permalink: pretty